site_name: Документация
site_url: https://bely.remirk.space/
repo_url: https://github.com/CoplandTech/wiki
copyright: © Plan7 2011 - 2025

docs_dir: docs/ 
site_dir: site/
plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  language: ru
  logo: assets/images/favicon/icon.svg
  favicon: assets/images/favicon/icon.png
  features:
    # Настройки навигационной
    - navigation.tracking 
    - navigation.instant
    - navigation.tabs 
    - navigation.top 
    - navigation.path
    - toc.follow
    - navigation.indexes
    # Настройка поиска
    - search.highlight
    - search.share
    # Подвал снизу
    - navigation.footer
    # Код
    - content.code.copy
    - content.code.annotate
    # Табы
    - content.tabs.link
    # Tooltrips
    - content.tooltips
  icon:
    annotation: material/star-four-points-circle

  palette: 
    # Palette toggle for light mode
    
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

extra:
  analytics: 
    provider: google
    property: foobar
    feedback:
      title: Была ли эта страница полезна?
      ratings:
        - icon: material/thumb-up-outline
          name: Эта страница помогла!
          data: 1
          note: >-
            Спасибо за Ваш отзыв.
        - icon: material/thumb-down-outline
          name: Эта страница не помогла!
          data: -1
          note: >- 
            Нам жаль...
    
extra_javascript:
  - assets/function/main-nav-tree/main.js
  - assets/function/hotkeys/main.js
  - assets/function/report-error/main.js
extra_css:
  - assets/function/main-nav-tree/main.css
  - assets/function/hotkeys/main.css
  - assets/function/report-error/main.css

markdown_extensions:
  - attr_list # Annotations, Buttons, Grids, Icons/Emojis, Images, Tooltips
  - pymdownx.superfences # Admonitions, Annotations, Code blocks, Content tabs
  - md_in_html # Annotations, Grids, Images
  - admonition # Admonitions
  - pymdownx.details # Admonitions
  - tables # Data tables
  - abbr # Tooltips
  - footnotes # Footnotes
  - pymdownx.critic # Formatting
  - pymdownx.caret # Formatting
  - pymdownx.keys # Formatting
  - pymdownx.mark # Formatting
  - pymdownx.tilde # Formatting
  - pymdownx.blocks.caption # Images
  - def_list # Lists
  - pymdownx.inlinehilite # Code blocks
  - pymdownx.snippets # Code blocks, Tooltips
  # Lists
  - pymdownx.tasklist: 
      custom_checkbox: true
  # Code blocks
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Content tabs
  - pymdownx.tabbed: 
      alternate_style: true
  # Icons/Emojis
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Permalink
  - toc:
      permalink: true
      permalink_title: Постоянная ссылка

nav:
  - Home: index.md
  - Cat 1:
    - pages/cat1/Getting started.md
    - pages/cat1/Creating your site.md
    - "Cat 1-1":
      - pages/cat1/cat1-1/iae.md
  - Cat 2: 
    - About: pages/cat2/about.md